baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Roby Van Damme"

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

[params]
  description = "Roby Van Damme's blog"
  mainSections = ['posts']
  toc = false # set to false to disable table of contents 'globally'
  tocOpen = false # set to true to open table of contents by default
  goToTop = false # set to false to disable 'go to top' button
  # additionalScripts = ['js/custom.js', 'js/custom-2.js']
  # Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
  # Your custom scripts will be concatenated to one file `custom.js`.
  # When building for production it will be minified.
  # The file `custom.js` is loaded on each page (before body tag ends).
  dateFormat = "" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.
  # See https://gohugo.io/functions/time/format/ for available date formats.
  rssFeedDescription = "summary" # available options: 1) summary 2) full
  # summary - includes a short summary of the blog post in the RSS feed. Generated using Hugo .Summary .
  # full - includes full blog post in the RSS feed. Generated using Hugo .Content .
  # By default (or if nothing is specified), summary is used.

[params.author]
  avatar = "me.png" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Roby Van Damme"
  name = "Roby Van Damme"
  description = "Software developer & consultant"

[menu]
[[menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
[[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20