baseURL = 'https://robyvandamme.github.io'

[params.plausible]
  enable = true  # Whether to enable plausible tracking
  domain = "robyvandamme.github.io"  # Plausible "domain" name/id in your dashboard